### ISSUE TITLE
Error on compile - Android

### ISSUE THREAD

**Issue by graphefruit** [api-ai/api-ai-cordova-sample#3]
Hello,

tried your sample and after adding the plugin cordova build crashes:
```
C:\Users\XXX\Documents\test2>cordova build android --stacktrace
ANDROID_HOME=C:\Users\XXX\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files (x86)\Java\jdk1.7.0_55

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.2.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.1/support-v4-23.2.1.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.1/support-v4-23.2.1.jar
         file:/C:/Users/XXX/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.2.1/support-v4-23.2.1.pom
         file:/C:/Users/XXX/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.2.1/support-v4-23.2.1.jar
         file:/C:/Users/XXX/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.2.1/support-v4-23.2.1.pom
         file:/C:/Users/XXX/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/support-v4/23.2.1/support-v4-23.2.1.jar
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
 or --debug option to get more log output.
BUILD FAILED
```

Any suggestions?
CLI: 6.1
Node version v0.12.2

**Comment by xVir** [comment]
Hi, @graphefruit 

Could you please try to update your Android SDK?
![screen 2016-04-04 12 28 57](https://cloud.githubusercontent.com/assets/278221/14239750/ec362462-fa60-11e5-91c4-739a49717d73.png)

Especially please pay attention to **Android Support Library** and **Google Repository**

Thanks!

**Comment by graphefruit** [comment]
Hi @xVir.Thanks for your help, the App can be compiled now.
Tried to test voice / text without succeed.
See pictures. Any idea?
![screenshot_20160404-091214](https://cloud.githubusercontent.com/assets/6260244/14240486/8d0935e4-fa45-11e5-992b-dab0637af78a.png)
![screenshot_20160404-091135](https://cloud.githubusercontent.com/assets/6260244/14240485/8d0817d6-fa45-11e5-8063-ff611a00ec81.png)

**Comment by graphefruit** [comment]
Hi @xVir I just solved it with outlining the setRecognitionResultsCallback.
Now I step into a new problem, if I set the language to German and try to speak something the app crashes. In english it works.

Any further idea?
Greetings & Thanks
Graphefruit

**Comment by xVir** [comment]
Hi, @graphefruit 
Could you please send me some part of your code in which ApiAIPlugin initialized and used?
Thanks!

**Comment by graphefruit** [comment]
Hi @xVir I'm using this repo without anything else.
I uploaded an ZIP file with the config.xml aswell as the WWW-Folder.
http://www.file-upload.net/download-11453940/www.ZIP.html
PS: Sadly i can't upload a zip here (error...don't know why) so I used a file upload.

Hopefully this helps you.
Thanks & Greetings

**Comment by xVir** [comment]
@graphefruit I just made some changes, please update your sources from the repository

**Comment by graphefruit** [comment]
@xVir Thank you! Works now like a charm.
Thanks for your time & help.

**Comment by xVir** [comment]
@graphefruit you are welcome!
Feel free to ask any questions,

Thanks!
